### ISSUE TITLE
UNKNOWN - Cannot parse JSON from Graylog2 API error

### ISSUE THREAD

**Issue by ankush-grover-3pg** [catinello/nagios-check-graylog2#1]
Hi,

I am running Graylog 2.1.2 version on Centos 7 64-bit and I am running Icinga2 on Centos 6 64-bit. When I try to check the performance of graylog2 through Icinga I am getting the "UNKNOWN - Cannot parse JSON from Graylog2 API" error 

./check_graylog2 -l https://syslogsrv-ndi.example.com:9000/ -u admin -p server -insecure

UNKNOWN - Can not parse JSON from Graylog2 API|time=0.000000;;;; total=0;;;; sources=0;;;; throughput=0;;;; index_failures=0;;;;

What could be the issue, any missing package etc..?/

Thanks & Regards
Ankush Grover

**Comment by catinello** [comment]
You're not getting a JSON response with the given parameters. This means either your credentials are wrong or you're using the wrong address data or your API isn't working properly. 

Are you sure that you are using Port 9000 for the API and not Port 12900? You may want to switch ports.

Alternatively you can enable debugging to display the "body" of the reply from your request. You can do that by setting an environment variable. `export NCG2=debug`
