### ISSUE TITLE
On  Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by bubba198** [catinello/nagios-check-graylog2#2]
UNKNOWN - Can not parse JSON from Graylog2 API|time=0.000000;;;; total=0;;;; sources=0;;;; throughput=0;;;; index_failures=0;;;;

Running the latest Graylog and the API works fine in a browser - Chrome used for testing it

`/usr/local/nagios/libexec/check_graylog2 -l http://192.168.1.95:9000/api/ -u admin -p admin`

**Comment by catinello** [comment]
Please try your command with the prefix `NCG2=debug` and paste the output in here.

`NCG2=debug /usr/local/nagios/libexec/check_graylog2 -l http://192.168.1.95:9000/api/ -u admin -p admin`

**Comment by bubba198** [comment]
Hi @catinello here's the output:

```
boyan@nagios3:~$ NCG2=debug /usr/local/nagios/libexec/check_graylog2 -l http://192.168.1.95:9000/api/ -u admin -p admin
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="/assets/favicon.png">

  </head>
  <body>
    <script src="/config.js"></script>
    <script src="/assets/vendor.js"></script>

    <script src="/assets/polyfill.35e28e4da7743596569a.js"></script>

    <script src="/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js"></script>

    <script src="/assets/plugin/org.graylog.plugins.map.MapWidgetPlugin/plugin.org.graylog.plugins.map.MapWidgetPlugin.5011f2ebff35ef956f1b.js"></script>

    <script src="/assets/plugin/org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin/plugin.org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin.3e5ff59c400f972516bd.js"></script>

    <script src="/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.13edb0af11e27a17b001.js"></script>

    <script src="/assets/app.35e28e4da7743596569a.js"></script>

  </body>
</html>

invalid character '<' looking for beginning of value
UNKNOWN - Can not parse JSON from Graylog2 API|time=0.000000;;;; total=0;;;; sources=0;;;; throughput=0;;;; index_failures=0;;;;
boyan@nagios3:~$

```

**Comment by catinello** [comment]
You're obviously receiving an HTML document. It is supposed to be a JSON though.

Which graylog2 version are you using? Are you sure that your path is correctly configured and your API is not on Port 12900?

**Comment by bubba198** [comment]
Thanks @catinello 

I'm using Version: 2.2.3+7adc951, codename Stiegl

Here's the API URL straight from the "node information" screen:

Transport address: http://192.168.1.95:9000/api/

Also just to be sure I did a simple telnet to port 12900 and it times out; there isn't anything listening to TCP 12900 either if I do the netstat on the VM itself...

**Comment by s0l4r** [comment]
I have the same issue. 
I think Graylog has changed the API.

My Graylog REST API URL is http://0.0.0.0:9000/api/

When testing with another similar plugin to yours, it doesn't work either. The returning code from Graylog API is in HTML, but it should be JSON. I think that you have to pass "Accept: application/json" header, because when testing the API URL with curl, it gives JSON back.

```
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' 'http://localhost:9000/api/system/sessions' -d '{"username":"admin", "password":"xxx", "host":""}'
HTTP/1.1 200 OK
X-Graylog-Node-ID: 1234
Content-Type: application/json
Date: Tue, 30 May 2017 16:08:51 GMT
Content-Length: 98

{"valid_until":"2017-05-31T00:08:52.162+0000","session_id":"41b833f9-0f90-463c-84c2-ecabce2c53e3"}
```

```
ngrep -d eth0 port 9000
interface: eth0 (10.22.192.72/255.255.255.248)
filter: ( port 9000 ) and ((ip || ip6) || (vlan && (ip || ip6)))
###
#######
T 10.22.192.72:51469 -> 10.22.192.72:9000 [AP]
  GET /system HTTP/1.1..Host: 10.22.192.72:9000..User-Agent: Go-http-client/1.1..Authorization: Basic YWRtaW46ZnVqaXRzdQ==..Accept-Encoding: gzip....                        
###

```

**Comment by kahluagenie** [comment]
Having the same problem of html coming back even though I see json being returned at the same endpoint with curl. @s0l4r's suggestion on Accept header sounds on point.

**Comment by mrmcox** [comment]
I too am having this issue, any suggestions of a fix would be great.
![image](https://cloud.githubusercontent.com/assets/29230824/26831623/d08ce4fc-4ac4-11e7-9303-148129a8fb18.png)
![image](https://cloud.githubusercontent.com/assets/29230824/26831668/ee6de48a-4ac4-11e7-92c5-2f3d611c5abf.png)

**Comment by kahluagenie** [comment]
I created a pull request to fix the issue, but if you don't want to wait, it's easy to build the project (I'm not providing the executable). Just install Go and run this command inside the project dir:
`env GOOS=linux GOARCH=amd64 go build -v .`

**Comment by mrmcox** [comment]
@kahluagenie 
I have made the changes using the go code and command you provided, thank you for that!

I am now getting a 404 HTTP response. Any ideas?

Thanks again.

**Comment by kahluagenie** [comment]
@mrmcox assuming you're on the HEAD of my fork, I would try inspecting the URL that the code tries to call. Can you try something like this on line 169:
`fmt.Printf("Making a request to %s", req.URL)`

See if that URL is correct and is not misformatted in any way.

**Comment by mrmcox** [comment]
I have got it all working :-) 

Thanks very much to @catinello and @kahluagenie

**Comment by catinello** [comment]
Thanks all and especially @kahluagenie for the pr. Patch lgtm and was merged.

**Comment by s0l4r** [comment]
Thanks, it's working!
