### ISSUE TITLE
Trouble executing in librenms

### ISSUE THREAD

**Issue by netpacket** [catinello/nagios-check-graylog2#9]
I have successfully pulled down the script and installed dependencies. I am able to run the script through the command line; however importing it into librenms is causing an service error. Usually this is because of either the wrong arguments or firewall issues. 

I copied the command line arguments. I am able to hit the graylog instance with script.

Any other recommendations to check the error?

**Comment by catinello** [comment]
You may want to try debug mode on the cli to get more information. https://github.com/catinello/nagios-check-graylog2#debugging

Other than that I'm afraid that I can't help you and it sounds more like a libreNMS configuration issue to me.

**Comment by netpacket** [comment]
Hmmm, the complaint with librenms is that the -H flag is not declared.

**Comment by catinello** [comment]
This is not an issue of this tool, as it is mainly targeted for Nagios usage. I don't know exactly what this "-H flag" thing is about but as of today it is unused. You are welcome to send a PR if that change makes sense for the general user.
